language: php

php:
  - 5.6
  - 7.0


before_install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install

# to avoid generating magento2's files
before_script:
  - mv tests/mock/* vendor/magento/module-catalog/Api/Data

script:
  - php vendor/bin/phpunit -c ./build/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls

env:
  global:
    - secure: "HgLwbkOZTuHdatYdTsqSkDOphiwUbhC5Guskca1fPZut94VRmrvA8vsGOIsW3SIdqm2lx21eUegyaCpoBYIMTk3kiK4fJs9p3/KIG/pTfz7HzFGuA1hgeWhZ2bTbArQwUI3LtQ0UH7BnWdmh0g01HsAfFJ0gH72d2LImEG/YKoSqHErsdF/Mq7ZFE0Z7JrVAu0TmBZFDqNGvkZAaE5wbDlfDzvuf5bJ/U8WauIiXEjCWNjKtWh5NDVLZ48WhYCft7hjb8OgoE0+nuVJTXGJgdx5m5NURDMm8F4T7WmUVC9TzNFCtAD5GC8YrKBnrpcPJlfW3uH4kIXlUXRnsqg54OrGLGvFfTieMGQB0kGflDrTaVMISortt7QWlBOMuumEspqRinfXaaiUwAt7xSiUDiuz3gHxrR4KiI2mmrH5KTDf3NYHXwBjDckU+fQ2JLBY8xw6viy0X8p2AxYfs+rMes2NdS8r6SaOSZgNguF2p67nXKpzq4EGeljbq6BvnnIoiA3GchJhZASAu3HO9FoJxJ47/P25W3CNCpeR6DhzS4GGPinVM7P1n31hZ3ydON9LCTXXMrof2lFbtpOkkNtqYNDkiZ9V4Gxp18psPNns99oi2tqMBkbbnGQUIcigBYgVbQSD7naf37/evevUevDZZRstMq8YL73/shnOc4ZQhEcQ="
    - secure: "HpzegGLlhDRIhGnrnzpYXpvStYXeGOsifaS7J5w+pv2DbXiUc30Y7sis4tkEdMH1CUcvp3saqb5EZsMTxMARiWHDA13xtzm6bkZkf1ka6hNWxL3wMxRef0dGPusiuOLm+bcVq6RuptC80fCKjuXHKd1MfISgpCtaTSmLRo9dbuaHISEwIQnIpHiuXe7dUndyCkjcL2h6PusCXtbo1Ui2AFcLWZhv8OAkqEzWFLAO0b2R2LPZUumJe23PYV0J19Kk8sV5Pf9XGIuVXSBrVPXLwzaYJhHVB5OQ0AxXbtH0JRALASWHCOI2wCRt1NGPbjWaZK5eNPvoRcjuG5A/A3lZTSHGAH8U9Yo96HGOvjOGsuilGu2g5dcmBoeIQG6DR6tPWn6PFnmA47V8J+q3smgKglUOR8+suulTyQAYHgks4JpW8gAp3Q401WakTmmplpZcG1t08DbcBYJwinT7meMZfhxmSlBnwYrJ96T4YbAhFPQGZ5/sGSTrQAALg8lfTglMT9ExjXvkllP/HqBBYajVAeU5DXHKRoPHBIzGGeqNQ86E2tdUvizZym4P3NwegdL2cI2wRUHiI3sJ+xz3hGfNBnQpqunib+cSOPswhrd4TH4gviXrKjoN2NpQ5HEi0cWaTtKE3wxqcQPn85WrgFNkZby5nSX981n7IkOJvB4iaOs="